modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="dmz_logo.png"
credits="Thanks to Toji71 for helping us with the Builds."
authors="${mod_authors}"
description='''${mod_description}'''
displayTest = "MATCH_VERSION"
displayURL="https://discord.dragonminez.com/"

[[mixins]]
config="dragonminez.mixins.json"

[[dependencies.dragonminez]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.dragonminez]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.dragonminez]]
    modId="geckolib"
    mandatory=true
    versionRange="${geckolib_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.dragonminez]]
    modId="terrablender"
    mandatory=false
    versionRange="${terrablender_version_range}"
    ordering="AFTER"
    side="BOTH"

